# Histograms and Density Charts

# Some new geometries like Histograms and Density Charts
# histograms r also statistics so both geometry and statistics

# Before this we only work with points and lines geometry

library(ggplot2)

getwd()
setwd("/Users/sylvia/Desktop/R_Data")

stats <- read.csv("P2-Movie-Ratings.csv")

colnames(stats) <- c("Film","Genre","CriticRating","AudienceRating",
                     "Budgetmillion","year")

# Create histogram
# So histogram requires only 1 aesthetics x and other side (y) has
# a variable count which is generated by R thats y its not just a 
# geometry but also a statistic as R is aggregating values. first of
# all it creates these bins for u and then its aggregating your rows
# or ur observations into these bins n thats where the statistical 
# part comes from.

s <- ggplot(data = stats, aes(x = Budgetmillion))
s + geom_histogram(binwidth = 10)

# Add colour
s + geom_histogram(binwidth = 10, aes(fill =  Genre))
# add border
# Colour is to add border/ outline while fill to fill the colour
s + geom_histogram(binwidth = 10, aes(fill = Genre), colour = "Black")

# Density Charts
# They represent probability density function

s + geom_density(aes(fill = Genre))
s + geom_density(aes(fill = Genre),position = "stack")





